CREATE TABLE CS_MatchPlayerDamageReport(
    ID MEDIUMINT NOT NULL AUTO_INCREMENT,
    MatchPlayer_UUID VARCHAR(36),
    Type ENUM(
        "Guardians",
        "Falling Damage",
        "Collision Damage",
        "Melee Damage",
        "Explosion",
        "Magnum Pistol",
        "Plasma Pistol",
        "Needler",
        "SMG",
        "Plasma Rifle",
        "Battle Rifle",
        "Carbine",
        "Shotgun",
        "Sniper Rifle",
        "Beam Rifle",
        "Brute Plasma Rifle",
        "Rocket Launcher",
        "Flak Cannon",
        "Brute Shot",
        "Disintegrator",
        "Sentinel Beam",
        "Sentinel RPG",
        "Energy Sword",
        "Frag Grenade",
        "Plasma Grenade",
        "Flag Melee Damage",
        "Bomb Melee Damage",
        "Ball Melee Damage",
        "Human Turret",
        "Plasma Turret",
        "Banshee",
        "Ghost",
        "Mongoose",
        "Scorpion",
        "Spectre Driver",
        "Spectre Gunner",
        "Warthog Driver",
        "Warthog Gunner",
        "Wraith",
        "Tank",
        "Bomb Explosion Damage"
     ),
    Kills SMALLINT,
    Deaths SMALLINT,
    Betrayals SMALLINT,
    Suicides SMALLINT,
    ShotsFired SMALLINT,
    ShotsHit SMALLINT,
    Headshots SMALLINT,
    PRIMARY KEY(ID),
    FOREIGN KEY(MatchPlayer_UUID)
        REFERENCES CS_MatchPlayer(UUID)
) Engine=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;