CREATE TABLE CS_Player(
    XUID BIGINT UNSIGNED,
    Gamertag VARCHAR(16),
    PrimaryColor TINYINT,
    SecondaryColor TINYINT,
    PrimaryEmblem TINYINT,
    SecondaryEmblem TINYINT,
    EmblemForeground TINYINT,
    EmblemBackground TINYINT,
    EmblemToggle TINYINT,
    PlayerModel TINYINT,
    Nameplate TINYINT,
    Kills SMALLINT DEFAULT 0,
    Assists SMALLINT DEFAULT 0,
    Betrayals SMALLINT DEFAULT 0,
    Suicides SMALLINT DEFAULT 0,
    BestSpree SMALLINT DEFAULT 0,
    TimeAlive SMALLINT DEFAULT 0,
    FlagScores SMALLINT DEFAULT 0,
    FlagSteals SMALLINT DEFAULT 0,
    FlagSaves SMALLINT DEFAULT 0,
    FlagUnk SMALLINT DEFAULT 0,
    BombScores SMALLINT DEFAULT 0,
    BombKills SMALLINT DEFAULT 0,
    BombGrabs SMALLINT DEFAULT 0,
    BallScore SMALLINT DEFAULT 0,
    BallKills SMALLINT DEFAULT 0,
    BallCarrierKills SMALLINT DEFAULT 0,
    KingKillsAsKing SMALLINT DEFAULT 0,
    KingKilledKings SMALLINT DEFAULT 0,
    JuggKilledJuggs SMALLINT DEFAULT 0,
    JuggKillsAsJugg SMALLINT DEFAULT 0,
    JuggTime SMALLINT DEFAULT 0,
    TerrTaken SMALLINT DEFAULT 0,
    TerrLost SMALLINT DEFAULT 0,
    PRIMARY KEY(XUID)
) Engine=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
