<?php
    
    class MatchPlayerWeapon {
        public $MatchPlayer_UUID;
        public $MagnumKills;
        public $MagnumDeaths;
        public $MagnumSuicide;
        public $MagnumShotsFired;
        public $MagnumShotsHit;
        public $MagnumHeadshot;
        public $PlasmaPistolKills;
        public $PlasmaPistolDeaths;
        public $PlasmaPistolSuicide;
        public $PlasmaPistolShotsFired;
        public $PlasmaPistolShotsHit;
        public $PlasmaPistolHeadshot;
        public $NeedlerKills;
        public $NeedlerDeaths;
        public $NeedlerSuicide;
        public $NeedlerShotsFired;
        public $NeedlerShotsHit;
        public $NeedlerHeadshot;
        public $SubMachineGunKills;
        public $SubMachineGunDeaths;
        public $SubMachineGunSuicide;
        public $SubMachineGunShotsFired;
        public $SubMachineGunShotsHit;
        public $SubMachineGunHeadshot;
        public $PlasmaRifleKills;
        public $PlasmaRifleDeaths;
        public $PlasmaRifleSuicide;
        public $PlasmaRifleShotsFired;
        public $PlasmaRifleShotsHit;
        public $PlasmaRifleHeadshot;
        public $BattleRifleKills;
        public $BattleRifleDeaths;
        public $BattleRifleSuicide;
        public $BattleRifleShotsFired;
        public $BattleRifleShotsHit;
        public $BattleRifleHeadshot;
        public $CarbineKills;
        public $CarbineDeaths;
        public $CarbineSuicide;
        public $CarbineShotsFired;
        public $CarbineShotsHit;
        public $CarbineHeadshot;
        public $ShotgunKills;
        public $ShotgunDeaths;
        public $ShotgunSuicide;
        public $ShotgunShotsFired;
        public $ShotgunShotsHit;
        public $ShotgunHeadshot;
        public $SniperRifleKills;
        public $SniperRifleDeaths;
        public $SniperRifleSuicide;
        public $SniperRifleShotsFired;
        public $SniperRifleShotsHit;
        public $SniperRifleHeadshot;
        public $BeamRifleKills;
        public $BeamRifleDeaths;
        public $BeamRifleSuicide;
        public $BeamRifleShotsFired;
        public $BeamRifleShotsHit;
        public $BeamRifleHeadshot;
        public $BrutePlasmaRifleKills;
        public $BrutePlasmaRifleDeaths;
        public $BrutePlasmaRifleSuicide;
        public $BrutePlasmaRifleShotsFired;
        public $BrutePlasmaRifleShotsHit;
        public $BrutePlasmaRifleHeadshot;
        public $RocketLauncherKills;
        public $RocketLauncherDeaths;
        public $RocketLauncherSuicide;
        public $RocketLauncherShotsFired;
        public $RocketLauncherShotsHit;
        public $RocketLauncherHeadshot;
        public $FuelRodCannonKills;
        public $FuelRodCannonDeaths;
        public $FuelRodCannonSuicide;
        public $FuelRodCannonShotsFired;
        public $FuelRodCannonShotsHit;
        public $FuelRodCannonHeadshot;
        public $BruteshotKills;
        public $BruteshotDeaths;
        public $BruteshotSuicide;
        public $BruteshotShotsFired;
        public $BruteshotShotsHit;
        public $BruteshotHeadshot;
        public $Unused1Kills;
        public $Unused1Deaths;
        public $Unused1Suicide;
        public $Unused1ShotsFired;
        public $Unused1ShotsHit;
        public $Unused1Headshot;
        public $SentinalBeamKills;
        public $SentinalBeamDeaths;
        public $SentinalBeamSuicide;
        public $SentinalBeamShotsFired;
        public $SentinalBeamShotsHit;
        public $SentinalBeamHeadshot;
        public $Unused2Kills;
        public $Unused2Deaths;
        public $Unused2Suicide;
        public $Unused2ShotsFired;
        public $Unused2ShotsHit;
        public $Unused2Headshot;
        public $EnergySwordKills;
        public $EnergySwordDeaths;
        public $EnergySwordSuicide;
        public $EnergySwordShotsFired;
        public $EnergySwordShotsHit;
        public $EnergySwordHeadshot;
        public $FragGrenadeKills;
        public $FragGrenadeDeaths;
        public $FragGrenadeSuicide;
        public $FragGrenadeShotsFired;
        public $FragGrenadeShotsHit;
        public $FragGrenadeHeadshot;
        public $PlasmaGrenadeKills;
        public $PlasmaGrenadeDeaths;
        public $PlasmaGrenadeSuicide;
        public $PlasmaGrenadeShotsFired;
        public $PlasmaGrenadeShotsHit;
        public $PlasmaGrenadeHeadshot;
        public $CTFFlagKills;
        public $CTFFlagDeaths;
        public $CTFFlagSuicide;
        public $CTFFlagShotsFired;
        public $CTFFlagShotsHit;
        public $CTFFlagHeadshot;
        public $AssaultBombKills;
        public $AssaultBombDeaths;
        public $AssaultBombSuicide;
        public $AssaultBombShotsFired;
        public $AssaultBombShotsHit;
        public $AssaultBombHeadshot;
        public $OddballSkullKills;
        public $OddballSkullDeaths;
        public $OddballSkullSuicide;
        public $OddballSkullShotsFired;
        public $OddballSkullShotsHit;
        public $OddballSkullHeadshot;
        public $HumanTurretKills;
        public $HumanTurretDeaths;
        public $HumanTurretSuicide;
        public $HumanTurretShotsFired;
        public $HumanTurretShotsHit;
        public $HumanTurretHeadshot;
        public $CovenantTurretKills;
        public $CovenantTurretDeaths;
        public $CovenantTurretSuicide;
        public $CovenantTurretShotsFired;
        public $CovenantTurretShotsHit;
        public $CovenantTurretHeadshot;
        public $BansheeKills;
        public $BansheeDeaths;
        public $BansheeSuicide;
        public $BansheeShotsFired;
        public $BansheeShotsHit;
        public $BansheeHeadshot;
        public $GhostKills;
        public $GhostDeaths;
        public $GhostSuicide;
        public $GhostShotsFired;
        public $GhostShotsHit;
        public $GhostHeadshot;
        public $Unused3Kills;
        public $Unused3Deaths;
        public $Unused3Suicide;
        public $Unused3ShotsFired;
        public $Unused3ShotsHit;
        public $Unused3Headshot;
        public $ScorpionTurretKills;
        public $ScorpionTurretDeaths;
        public $ScorpionTurretSuicide;
        public $ScorpionTurretShotsFired;
        public $ScorpionTurretShotsHit;
        public $ScorpionTurretHeadshot;
        public $SpectreDriverKills;
        public $SpectreDriverDeaths;
        public $SpectreDriverSuicide;
        public $SpectreDriverShotsFired;
        public $SpectreDriverShotsHit;
        public $SpectreDriverHeadshot;
        public $SpectreTurrentKills;
        public $SpectreTurrentDeaths;
        public $SpectreTurrentSuicide;
        public $SpectreTurrentShotsFired;
        public $SpectreTurrentShotsHit;
        public $SpectreTurrentHeadshot;
        public $WarthogDriverKills;
        public $WarthogDriverDeaths;
        public $WarthogDriverSuicide;
        public $WarthogDriverShotsFired;
        public $WarthogDriverShotsHit;
        public $WarthogDriverHeadshot;
        public $WarthogTurretKills;
        public $WarthogTurretDeaths;
        public $WarthogTurretSuicide;
        public $WarthogTurretShotsFired;
        public $WarthogTurretShotsHit;
        public $WarthogTurretHeadshot;
        public $WraithKills;
        public $WraithDeaths;
        public $WraithSuicide;
        public $WraithShotsFired;
        public $WraithShotsHit;
        public $WraithHeadshot;
        public $ScorpionCannonKills;
        public $ScorpionCannonDeaths;
        public $ScorpionCannonSuicide;
        public $ScorpionCannonShotsFired;
        public $ScorpionCannonShotsHit;
        public $ScorpionCannonHeadshot;
        public $AssultBombKills;
        public $AssultBombDeaths;
        public $AssultBombSuicide;
        public $AssultBombShotsFired;
        public $AssultBombShotsHit;
        public $AssultBombHeadshot;
        public function __construct() {
            $get_arguments       = func_get_args();
            $number_of_arguments = func_num_args();
            if (method_exists($this, $method_name = '__construct'.$number_of_arguments)) {
                call_user_func_array(array($this, $method_name), $get_arguments);
            }
        }
        public function __construct2($matchPlayer_UUID, $jsonData){
            $this->MatchPlayer_UUID = $matchPlayer_UUID;
           $this->MagnumKills = $jsonData[0][0];
           $this->MagnumDeaths = $jsonData[0][1];
           $this->MagnumSuicide = $jsonData[0][2];
           $this->MagnumShotsFired = $jsonData[0][3];
           $this->MagnumShotsHit = $jsonData[0][4];
           $this->MagnumHeadshot = $jsonData[0][5];
           $this->PlasmaPistolKills = $jsonData[1][0];
           $this->PlasmaPistolDeaths = $jsonData[1][1];
           $this->PlasmaPistolSuicide = $jsonData[1][2];
           $this->PlasmaPistolShotsFired = $jsonData[1][3];
           $this->PlasmaPistolShotsHit = $jsonData[1][4];
           $this->PlasmaPistolHeadshot = $jsonData[1][5];
           $this->NeedlerKills = $jsonData[2][0];
           $this->NeedlerDeaths = $jsonData[2][1];
           $this->NeedlerSuicide = $jsonData[2][2];
           $this->NeedlerShotsFired = $jsonData[2][3];
           $this->NeedlerShotsHit = $jsonData[2][4];
           $this->NeedlerHeadshot = $jsonData[2][5];
           $this->SubMachineGunKills = $jsonData[3][0];
           $this->SubMachineGunDeaths = $jsonData[3][1];
           $this->SubMachineGunSuicide = $jsonData[3][2];
           $this->SubMachineGunShotsFired = $jsonData[3][3];
           $this->SubMachineGunShotsHit = $jsonData[3][4];
           $this->SubMachineGunHeadshot = $jsonData[3][5];
           $this->PlasmaRifleKills = $jsonData[4][0];
           $this->PlasmaRifleDeaths = $jsonData[4][1];
           $this->PlasmaRifleSuicide = $jsonData[4][2];
           $this->PlasmaRifleShotsFired = $jsonData[4][3];
           $this->PlasmaRifleShotsHit = $jsonData[4][4];
           $this->PlasmaRifleHeadshot = $jsonData[4][5];
           $this->BattleRifleKills = $jsonData[5][0];
           $this->BattleRifleDeaths = $jsonData[5][1];
           $this->BattleRifleSuicide = $jsonData[5][2];
           $this->BattleRifleShotsFired = $jsonData[5][3];
           $this->BattleRifleShotsHit = $jsonData[5][4];
           $this->BattleRifleHeadshot = $jsonData[5][5];
           $this->CarbineKills = $jsonData[6][0];
           $this->CarbineDeaths = $jsonData[6][1];
           $this->CarbineSuicide = $jsonData[6][2];
           $this->CarbineShotsFired = $jsonData[6][3];
           $this->CarbineShotsHit = $jsonData[6][4];
           $this->CarbineHeadshot = $jsonData[6][5];
           $this->ShotgunKills = $jsonData[7][0];
           $this->ShotgunDeaths = $jsonData[7][1];
           $this->ShotgunSuicide = $jsonData[7][2];
           $this->ShotgunShotsFired = $jsonData[7][3];
           $this->ShotgunShotsHit = $jsonData[7][4];
           $this->ShotgunHeadshot = $jsonData[7][5];
           $this->SniperRifleKills = $jsonData[8][0];
           $this->SniperRifleDeaths = $jsonData[8][1];
           $this->SniperRifleSuicide = $jsonData[8][2];
           $this->SniperRifleShotsFired = $jsonData[8][3];
           $this->SniperRifleShotsHit = $jsonData[8][4];
           $this->SniperRifleHeadshot = $jsonData[8][5];
           $this->BeamRifleKills = $jsonData[9][0];
           $this->BeamRifleDeaths = $jsonData[9][1];
           $this->BeamRifleSuicide = $jsonData[9][2];
           $this->BeamRifleShotsFired = $jsonData[9][3];
           $this->BeamRifleShotsHit = $jsonData[9][4];
           $this->BeamRifleHeadshot = $jsonData[9][5];
           $this->BrutePlasmaRifleKills = $jsonData[10][0];
           $this->BrutePlasmaRifleDeaths = $jsonData[10][1];
           $this->BrutePlasmaRifleSuicide = $jsonData[10][2];
           $this->BrutePlasmaRifleShotsFired = $jsonData[10][3];
           $this->BrutePlasmaRifleShotsHit = $jsonData[10][4];
           $this->BrutePlasmaRifleHeadshot = $jsonData[10][5];
           $this->RocketLauncherKills = $jsonData[11][0];
           $this->RocketLauncherDeaths = $jsonData[11][1];
           $this->RocketLauncherSuicide = $jsonData[11][2];
           $this->RocketLauncherShotsFired = $jsonData[11][3];
           $this->RocketLauncherShotsHit = $jsonData[11][4];
           $this->RocketLauncherHeadshot = $jsonData[11][5];
           $this->FuelRodCannonKills = $jsonData[12][0];
           $this->FuelRodCannonDeaths = $jsonData[12][1];
           $this->FuelRodCannonSuicide = $jsonData[12][2];
           $this->FuelRodCannonShotsFired = $jsonData[12][3];
           $this->FuelRodCannonShotsHit = $jsonData[12][4];
           $this->FuelRodCannonHeadshot = $jsonData[12][5];
           $this->BruteshotKills = $jsonData[13][0];
           $this->BruteshotDeaths = $jsonData[13][1];
           $this->BruteshotSuicide = $jsonData[13][2];
           $this->BruteshotShotsFired = $jsonData[13][3];
           $this->BruteshotShotsHit = $jsonData[13][4];
           $this->BruteshotHeadshot = $jsonData[13][5];
           $this->Unused1Kills = $jsonData[14][0];
           $this->Unused1Deaths = $jsonData[14][1];
           $this->Unused1Suicide = $jsonData[14][2];
           $this->Unused1ShotsFired = $jsonData[14][3];
           $this->Unused1ShotsHit = $jsonData[14][4];
           $this->Unused1Headshot = $jsonData[14][5];
           $this->SentinalBeamKills = $jsonData[15][0];
           $this->SentinalBeamDeaths = $jsonData[15][1];
           $this->SentinalBeamSuicide = $jsonData[15][2];
           $this->SentinalBeamShotsFired = $jsonData[15][3];
           $this->SentinalBeamShotsHit = $jsonData[15][4];
           $this->SentinalBeamHeadshot = $jsonData[15][5];
           $this->Unused2Kills = $jsonData[16][0];
           $this->Unused2Deaths = $jsonData[16][1];
           $this->Unused2Suicide = $jsonData[16][2];
           $this->Unused2ShotsFired = $jsonData[16][3];
           $this->Unused2ShotsHit = $jsonData[16][4];
           $this->Unused2Headshot = $jsonData[16][5];
           $this->EnergySwordKills = $jsonData[17][0];
           $this->EnergySwordDeaths = $jsonData[17][1];
           $this->EnergySwordSuicide = $jsonData[17][2];
           $this->EnergySwordShotsFired = $jsonData[17][3];
           $this->EnergySwordShotsHit = $jsonData[17][4];
           $this->EnergySwordHeadshot = $jsonData[17][5];
           $this->FragGrenadeKills = $jsonData[18][0];
           $this->FragGrenadeDeaths = $jsonData[18][1];
           $this->FragGrenadeSuicide = $jsonData[18][2];
           $this->FragGrenadeShotsFired = $jsonData[18][3];
           $this->FragGrenadeShotsHit = $jsonData[18][4];
           $this->FragGrenadeHeadshot = $jsonData[18][5];
           $this->PlasmaGrenadeKills = $jsonData[19][0];
           $this->PlasmaGrenadeDeaths = $jsonData[19][1];
           $this->PlasmaGrenadeSuicide = $jsonData[19][2];
           $this->PlasmaGrenadeShotsFired = $jsonData[19][3];
           $this->PlasmaGrenadeShotsHit = $jsonData[19][4];
           $this->PlasmaGrenadeHeadshot = $jsonData[19][5];
           $this->CTFFlagKills = $jsonData[20][0];
           $this->CTFFlagDeaths = $jsonData[20][1];
           $this->CTFFlagSuicide = $jsonData[20][2];
           $this->CTFFlagShotsFired = $jsonData[20][3];
           $this->CTFFlagShotsHit = $jsonData[20][4];
           $this->CTFFlagHeadshot = $jsonData[20][5];
           $this->AssaultBombKills = $jsonData[21][0];
           $this->AssaultBombDeaths = $jsonData[21][1];
           $this->AssaultBombSuicide = $jsonData[21][2];
           $this->AssaultBombShotsFired = $jsonData[21][3];
           $this->AssaultBombShotsHit = $jsonData[21][4];
           $this->AssaultBombHeadshot = $jsonData[21][5];
           $this->OddballSkullKills = $jsonData[22][0];
           $this->OddballSkullDeaths = $jsonData[22][1];
           $this->OddballSkullSuicide = $jsonData[22][2];
           $this->OddballSkullShotsFired = $jsonData[22][3];
           $this->OddballSkullShotsHit = $jsonData[22][4];
           $this->OddballSkullHeadshot = $jsonData[22][5];
           $this->HumanTurretKills = $jsonData[23][0];
           $this->HumanTurretDeaths = $jsonData[23][1];
           $this->HumanTurretSuicide = $jsonData[23][2];
           $this->HumanTurretShotsFired = $jsonData[23][3];
           $this->HumanTurretShotsHit = $jsonData[23][4];
           $this->HumanTurretHeadshot = $jsonData[23][5];
           $this->CovenantTurretKills = $jsonData[24][0];
           $this->CovenantTurretDeaths = $jsonData[24][1];
           $this->CovenantTurretSuicide = $jsonData[24][2];
           $this->CovenantTurretShotsFired = $jsonData[24][3];
           $this->CovenantTurretShotsHit = $jsonData[24][4];
           $this->CovenantTurretHeadshot = $jsonData[24][5];
           $this->BansheeKills = $jsonData[25][0];
           $this->BansheeDeaths = $jsonData[25][1];
           $this->BansheeSuicide = $jsonData[25][2];
           $this->BansheeShotsFired = $jsonData[25][3];
           $this->BansheeShotsHit = $jsonData[25][4];
           $this->BansheeHeadshot = $jsonData[25][5];
           $this->GhostKills = $jsonData[26][0];
           $this->GhostDeaths = $jsonData[26][1];
           $this->GhostSuicide = $jsonData[26][2];
           $this->GhostShotsFired = $jsonData[26][3];
           $this->GhostShotsHit = $jsonData[26][4];
           $this->GhostHeadshot = $jsonData[26][5];
           $this->Unused3Kills = $jsonData[27][0];
           $this->Unused3Deaths = $jsonData[27][1];
           $this->Unused3Suicide = $jsonData[27][2];
           $this->Unused3ShotsFired = $jsonData[27][3];
           $this->Unused3ShotsHit = $jsonData[27][4];
           $this->Unused3Headshot = $jsonData[27][5];
           $this->ScorpionTurretKills = $jsonData[28][0];
           $this->ScorpionTurretDeaths = $jsonData[28][1];
           $this->ScorpionTurretSuicide = $jsonData[28][2];
           $this->ScorpionTurretShotsFired = $jsonData[28][3];
           $this->ScorpionTurretShotsHit = $jsonData[28][4];
           $this->ScorpionTurretHeadshot = $jsonData[28][5];
           $this->SpectreDriverKills = $jsonData[29][0];
           $this->SpectreDriverDeaths = $jsonData[29][1];
           $this->SpectreDriverSuicide = $jsonData[29][2];
           $this->SpectreDriverShotsFired = $jsonData[29][3];
           $this->SpectreDriverShotsHit = $jsonData[29][4];
           $this->SpectreDriverHeadshot = $jsonData[29][5];
           $this->SpectreTurrentKills = $jsonData[30][0];
           $this->SpectreTurrentDeaths = $jsonData[30][1];
           $this->SpectreTurrentSuicide = $jsonData[30][2];
           $this->SpectreTurrentShotsFired = $jsonData[30][3];
           $this->SpectreTurrentShotsHit = $jsonData[30][4];
           $this->SpectreTurrentHeadshot = $jsonData[30][5];
           $this->WarthogDriverKills = $jsonData[31][0];
           $this->WarthogDriverDeaths = $jsonData[31][1];
           $this->WarthogDriverSuicide = $jsonData[31][2];
           $this->WarthogDriverShotsFired = $jsonData[31][3];
           $this->WarthogDriverShotsHit = $jsonData[31][4];
           $this->WarthogDriverHeadshot = $jsonData[31][5];
           $this->WarthogTurretKills = $jsonData[32][0];
           $this->WarthogTurretDeaths = $jsonData[32][1];
           $this->WarthogTurretSuicide = $jsonData[32][2];
           $this->WarthogTurretShotsFired = $jsonData[32][3];
           $this->WarthogTurretShotsHit = $jsonData[32][4];
           $this->WarthogTurretHeadshot = $jsonData[32][5];
           $this->WraithKills = $jsonData[33][0];
           $this->WraithDeaths = $jsonData[33][1];
           $this->WraithSuicide = $jsonData[33][2];
           $this->WraithShotsFired = $jsonData[33][3];
           $this->WraithShotsHit = $jsonData[33][4];
           $this->WraithHeadshot = $jsonData[33][5];
           $this->ScorpionCannonKills = $jsonData[34][0];
           $this->ScorpionCannonDeaths = $jsonData[34][1];
           $this->ScorpionCannonSuicide = $jsonData[34][2];
           $this->ScorpionCannonShotsFired = $jsonData[34][3];
           $this->ScorpionCannonShotsHit = $jsonData[34][4];
           $this->ScorpionCannonHeadshot = $jsonData[34][5];
           $this->AssultBombKills = $jsonData[35][0];
           $this->AssultBombDeaths = $jsonData[35][1];
           $this->AssultBombSuicide = $jsonData[35][2];
           $this->AssultBombShotsFired = $jsonData[35][3];
           $this->AssultBombShotsHit = $jsonData[35][4];
           $this->AssultBombHeadshot = $jsonData[35][5];
        }        

        public function __construct1($dataRow){
           $this->MatchPlayerUUID = $dataRow["MatchPlayer_UUID"];
           $this->MagnumKills = $dataRow["MagnumKills"];
           $this->MagnumDeaths = $dataRow["MagnumDeaths"];
           $this->MagnumSuicide = $dataRow["MagnumSuicides"];
           $this->MagnumShotsFired = $dataRow["MagnumShotsFired"];
           $this->MagnumShotsHit = $dataRow["MagnumShotsHit"];
           $this->MagnumHeadshot = $dataRow["MagnumHeadShot"];
           $this->PlasmaPistolKills = $dataRow["PlasmaPistolKills"];
           $this->PlasmaPistolDeaths = $dataRow["PlasmaPistolDeaths"];
           $this->PlasmaPistolSuicide = $dataRow["PlasmaPistolSuicides"];
           $this->PlasmaPistolShotsFired = $dataRow["PlasmaPistolShotsFired"];
           $this->PlasmaPistolShotsHit = $dataRow["PlasmaPistolShotsHit"];
           $this->PlasmaPistolHeadshot = $dataRow["PlasmaPistolHeadShot"];
           $this->NeedlerKills = $dataRow["NeedlerKills"];
           $this->NeedlerDeaths = $dataRow["NeedlerDeaths"];
           $this->NeedlerSuicide = $dataRow["NeedlerSuicides"];
           $this->NeedlerShotsFired = $dataRow["NeedlerShotsFired"];
           $this->NeedlerShotsHit = $dataRow["NeedlerShotsHit"];
           $this->NeedlerHeadshot = $dataRow["NeedlerHeadShot"];
           $this->SubMachineGunKills = $dataRow["SubMachineGunKills"];
           $this->SubMachineGunDeaths = $dataRow["SubMachineGunDeaths"];
           $this->SubMachineGunSuicide = $dataRow["SubMachineGunSuicides"];
           $this->SubMachineGunShotsFired = $dataRow["SubMachineGunShotsFired"];
           $this->SubMachineGunShotsHit = $dataRow["SubMachineGunShotsHit"];
           $this->SubMachineGunHeadshot = $dataRow["SubMachineGunHeadShot"];
           $this->PlasmaRifleKills = $dataRow["PlasmaRifleKills"];
           $this->PlasmaRifleDeaths = $dataRow["PlasmaRifleDeaths"];
           $this->PlasmaRifleSuicide = $dataRow["PlasmaRifleSuicides"];
           $this->PlasmaRifleShotsFired = $dataRow["PlasmaRifleShotsFired"];
           $this->PlasmaRifleShotsHit = $dataRow["PlasmaRifleShotsHit"];
           $this->PlasmaRifleHeadshot = $dataRow["PlasmaRifleHeadShot"];
           $this->BattleRifleKills = $dataRow["BattleRifleKills"];
           $this->BattleRifleDeaths = $dataRow["BattleRifleDeaths"];
           $this->BattleRifleSuicide = $dataRow["BattleRifleSuicides"];
           $this->BattleRifleShotsFired = $dataRow["BattleRifleShotsFired"];
           $this->BattleRifleShotsHit = $dataRow["BattleRifleShotsHit"];
           $this->BattleRifleHeadshot = $dataRow["BattleRifleHeadShot"];
           $this->CarbineKills = $dataRow["CarbineKills"];
           $this->CarbineDeaths = $dataRow["CarbineDeaths"];
           $this->CarbineSuicide = $dataRow["CarbineSuicides"];
           $this->CarbineShotsFired = $dataRow["CarbineShotsFired"];
           $this->CarbineShotsHit = $dataRow["CarbineShotsHit"];
           $this->CarbineHeadshot = $dataRow["CarbineHeadShot"];
           $this->ShotgunKills = $dataRow["ShotgunKills"];
           $this->ShotgunDeaths = $dataRow["ShotgunDeaths"];
           $this->ShotgunSuicide = $dataRow["ShotgunSuicides"];
           $this->ShotgunShotsFired = $dataRow["ShotgunShotsFired"];
           $this->ShotgunShotsHit = $dataRow["ShotgunShotsHit"];
           $this->ShotgunHeadshot = $dataRow["ShotgunHeadShot"];
           $this->SniperRifleKills = $dataRow["SniperRifleKills"];
           $this->SniperRifleDeaths = $dataRow["SniperRifleDeaths"];
           $this->SniperRifleSuicide = $dataRow["SniperRifleSuicides"];
           $this->SniperRifleShotsFired = $dataRow["SniperRifleShotsFired"];
           $this->SniperRifleShotsHit = $dataRow["SniperRifleShotsHit"];
           $this->SniperRifleHeadshot = $dataRow["SniperRifleHeadShot"];
           $this->BeamRifleKills = $dataRow["BeamRifleKills"];
           $this->BeamRifleDeaths = $dataRow["BeamRifleDeaths"];
           $this->BeamRifleSuicide = $dataRow["BeamRifleSuicides"];
           $this->BeamRifleShotsFired = $dataRow["BeamRifleShotsFired"];
           $this->BeamRifleShotsHit = $dataRow["BeamRifleShotsHit"];
           $this->BeamRifleHeadshot = $dataRow["BeamRifleHeadShot"];
           $this->BrutePlasmaRifleKills = $dataRow["BrutePlasmaRifleKills"];
           $this->BrutePlasmaRifleDeaths = $dataRow["BrutePlasmaRifleDeaths"];
           $this->BrutePlasmaRifleSuicide = $dataRow["BrutePlasmaRifleSuicides"];
           $this->BrutePlasmaRifleShotsFired = $dataRow["BrutePlasmaRifleShotsFired"];
           $this->BrutePlasmaRifleShotsHit = $dataRow["BrutePlasmaRifleShotsHit"];
           $this->BrutePlasmaRifleHeadshot = $dataRow["BrutePlasmaRifleHeadShot"];
           $this->RocketLauncherKills = $dataRow["RocketLauncherKills"];
           $this->RocketLauncherDeaths = $dataRow["RocketLauncherDeaths"];
           $this->RocketLauncherSuicide = $dataRow["RocketLauncherSuicides"];
           $this->RocketLauncherShotsFired = $dataRow["RocketLauncherShotsFired"];
           $this->RocketLauncherShotsHit = $dataRow["RocketLauncherShotsHit"];
           $this->RocketLauncherHeadshot = $dataRow["RocketLauncherHeadShot"];
           $this->FuelRodCannonKills = $dataRow["FuelRodCannonKills"];
           $this->FuelRodCannonDeaths = $dataRow["FuelRodCannonDeaths"];
           $this->FuelRodCannonSuicide = $dataRow["FuelRodCannonSuicides"];
           $this->FuelRodCannonShotsFired = $dataRow["FuelRodCannonShotsFired"];
           $this->FuelRodCannonShotsHit = $dataRow["FuelRodCannonShotsHit"];
           $this->FuelRodCannonHeadshot = $dataRow["FuelRodCannonHeadShot"];
           $this->BruteshotKills = $dataRow["BruteshotKills"];
           $this->BruteshotDeaths = $dataRow["BruteshotDeaths"];
           $this->BruteshotSuicide = $dataRow["BruteshotSuicides"];
           $this->BruteshotShotsFired = $dataRow["BruteshotShotsFired"];
           $this->BruteshotShotsHit = $dataRow["BruteshotShotsHit"];
           $this->BruteshotHeadshot = $dataRow["BruteshotHeadShot"];
           $this->Unused1Kills = $dataRow["Unused1Kills"];
           $this->Unused1Deaths = $dataRow["Unused1Deaths"];
           $this->Unused1Suicide = $dataRow["Unused1Suicides"];
           $this->Unused1ShotsFired = $dataRow["Unused1ShotsFired"];
           $this->Unused1ShotsHit = $dataRow["Unused1ShotsHit"];
           $this->Unused1Headshot = $dataRow["Unused1HeadShot"];
           $this->SentinalBeamKills = $dataRow["SentinalBeamKills"];
           $this->SentinalBeamDeaths = $dataRow["SentinalBeamDeaths"];
           $this->SentinalBeamSuicide = $dataRow["SentinalBeamSuicides"];
           $this->SentinalBeamShotsFired = $dataRow["SentinalBeamShotsFired"];
           $this->SentinalBeamShotsHit = $dataRow["SentinalBeamShotsHit"];
           $this->SentinalBeamHeadshot = $dataRow["SentinalBeamHeadShot"];
           $this->Unused2Kills = $dataRow["Unused2Kills"];
           $this->Unused2Deaths = $dataRow["Unused2Deaths"];
           $this->Unused2Suicide = $dataRow["Unused2Suicides"];
           $this->Unused2ShotsFired = $dataRow["Unused2ShotsFired"];
           $this->Unused2ShotsHit = $dataRow["Unused2ShotsHit"];
           $this->Unused2Headshot = $dataRow["Unused2HeadShot"];
           $this->EnergySwordKills = $dataRow["EnergySwordKills"];
           $this->EnergySwordDeaths = $dataRow["EnergySwordDeaths"];
           $this->EnergySwordSuicide = $dataRow["EnergySwordSuicides"];
           $this->EnergySwordShotsFired = $dataRow["EnergySwordShotsFired"];
           $this->EnergySwordShotsHit = $dataRow["EnergySwordShotsHit"];
           $this->EnergySwordHeadshot = $dataRow["EnergySwordHeadShot"];
           $this->FragGrenadeKills = $dataRow["FragGrenadeKills"];
           $this->FragGrenadeDeaths = $dataRow["FragGrenadeDeaths"];
           $this->FragGrenadeSuicide = $dataRow["FragGrenadeSuicides"];
           $this->FragGrenadeShotsFired = $dataRow["FragGrenadeShotsFired"];
           $this->FragGrenadeShotsHit = $dataRow["FragGrenadeShotsHit"];
           $this->FragGrenadeHeadshot = $dataRow["FragGrenadeHeadShot"];
           $this->PlasmaGrenadeKills = $dataRow["PlasmaGrenadeKills"];
           $this->PlasmaGrenadeDeaths = $dataRow["PlasmaGrenadeDeaths"];
           $this->PlasmaGrenadeSuicide = $dataRow["PlasmaGrenadeSuicides"];
           $this->PlasmaGrenadeShotsFired = $dataRow["PlasmaGrenadeShotsFired"];
           $this->PlasmaGrenadeShotsHit = $dataRow["PlasmaGrenadeShotsHit"];
           $this->PlasmaGrenadeHeadshot = $dataRow["PlasmaGrenadeHeadShot"];
           $this->CTFFlagKills = $dataRow["CTFFlagKills"];
           $this->CTFFlagDeaths = $dataRow["CTFFlagDeaths"];
           $this->CTFFlagSuicide = $dataRow["CTFFlagSuicides"];
           $this->CTFFlagShotsFired = $dataRow["CTFFlagShotsFired"];
           $this->CTFFlagShotsHit = $dataRow["CTFFlagShotsHit"];
           $this->CTFFlagHeadshot = $dataRow["CTFFlagHeadShot"];
           $this->AssaultBombKills = $dataRow["AssaultBombKills"];
           $this->AssaultBombDeaths = $dataRow["AssaultBombDeaths"];
           $this->AssaultBombSuicide = $dataRow["AssaultBombSuicides"];
           $this->AssaultBombShotsFired = $dataRow["AssaultBombShotsFired"];
           $this->AssaultBombShotsHit = $dataRow["AssaultBombShotsHit"];
           $this->AssaultBombHeadshot = $dataRow["AssaultBombHeadShot"];
           $this->OddballSkullKills = $dataRow["OddballSkullKills"];
           $this->OddballSkullDeaths = $dataRow["OddballSkullDeaths"];
           $this->OddballSkullSuicide = $dataRow["OddballSkullSuicides"];
           $this->OddballSkullShotsFired = $dataRow["OddballSkullShotsFired"];
           $this->OddballSkullShotsHit = $dataRow["OddballSkullShotsHit"];
           $this->OddballSkullHeadshot = $dataRow["OddballSkullHeadShot"];
           $this->HumanTurretKills = $dataRow["HumanTurretKills"];
           $this->HumanTurretDeaths = $dataRow["HumanTurretDeaths"];
           $this->HumanTurretSuicide = $dataRow["HumanTurretSuicides"];
           $this->HumanTurretShotsFired = $dataRow["HumanTurretShotsFired"];
           $this->HumanTurretShotsHit = $dataRow["HumanTurretShotsHit"];
           $this->HumanTurretHeadshot = $dataRow["HumanTurretHeadShot"];
           $this->CovenantTurretKills = $dataRow["CovenantTurretKills"];
           $this->CovenantTurretDeaths = $dataRow["CovenantTurretDeaths"];
           $this->CovenantTurretSuicide = $dataRow["CovenantTurretSuicides"];
           $this->CovenantTurretShotsFired = $dataRow["CovenantTurretShotsFired"];
           $this->CovenantTurretShotsHit = $dataRow["CovenantTurretShotsHit"];
           $this->CovenantTurretHeadshot = $dataRow["CovenantTurretHeadShot"];
           $this->BansheeKills = $dataRow["BansheeKills"];
           $this->BansheeDeaths = $dataRow["BansheeDeaths"];
           $this->BansheeSuicide = $dataRow["BansheeSuicides"];
           $this->BansheeShotsFired = $dataRow["BansheeShotsFired"];
           $this->BansheeShotsHit = $dataRow["BansheeShotsHit"];
           $this->BansheeHeadshot = $dataRow["BansheeHeadShot"];
           $this->GhostKills = $dataRow["GhostKills"];
           $this->GhostDeaths = $dataRow["GhostDeaths"];
           $this->GhostSuicide = $dataRow["GhostSuicides"];
           $this->GhostShotsFired = $dataRow["GhostShotsFired"];
           $this->GhostShotsHit = $dataRow["GhostShotsHit"];
           $this->GhostHeadshot = $dataRow["GhostHeadShot"];
           $this->Unused3Kills = $dataRow["Unused3Kills"];
           $this->Unused3Deaths = $dataRow["Unused3Deaths"];
           $this->Unused3Suicide = $dataRow["Unused3Suicides"];
           $this->Unused3ShotsFired = $dataRow["Unused3ShotsFired"];
           $this->Unused3ShotsHit = $dataRow["Unused3ShotsHit"];
           $this->Unused3Headshot = $dataRow["Unused3HeadShot"];
           $this->ScorpionTurretKills = $dataRow["ScorpionTurretKills"];
           $this->ScorpionTurretDeaths = $dataRow["ScorpionTurretDeaths"];
           $this->ScorpionTurretSuicide = $dataRow["ScorpionTurretSuicides"];
           $this->ScorpionTurretShotsFired = $dataRow["ScorpionTurretShotsFired"];
           $this->ScorpionTurretShotsHit = $dataRow["ScorpionTurretShotsHit"];
           $this->ScorpionTurretHeadshot = $dataRow["ScorpionTurretHeadShot"];
           $this->SpectreDriverKills = $dataRow["SpectreDriverKills"];
           $this->SpectreDriverDeaths = $dataRow["SpectreDriverDeaths"];
           $this->SpectreDriverSuicide = $dataRow["SpectreDriverSuicides"];
           $this->SpectreDriverShotsFired = $dataRow["SpectreDriverShotsFired"];
           $this->SpectreDriverShotsHit = $dataRow["SpectreDriverShotsHit"];
           $this->SpectreDriverHeadshot = $dataRow["SpectreDriverHeadShot"];
           $this->SpectreTurrentKills = $dataRow["SpectreTurrentKills"];
           $this->SpectreTurrentDeaths = $dataRow["SpectreTurrentDeaths"];
           $this->SpectreTurrentSuicide = $dataRow["SpectreTurrentSuicides"];
           $this->SpectreTurrentShotsFired = $dataRow["SpectreTurrentShotsFired"];
           $this->SpectreTurrentShotsHit = $dataRow["SpectreTurrentShotsHit"];
           $this->SpectreTurrentHeadshot = $dataRow["SpectreTurrentHeadShot"];
           $this->WarthogDriverKills = $dataRow["WarthogDriverKills"];
           $this->WarthogDriverDeaths = $dataRow["WarthogDriverDeaths"];
           $this->WarthogDriverSuicide = $dataRow["WarthogDriverSuicides"];
           $this->WarthogDriverShotsFired = $dataRow["WarthogDriverShotsFired"];
           $this->WarthogDriverShotsHit = $dataRow["WarthogDriverShotsHit"];
           $this->WarthogDriverHeadshot = $dataRow["WarthogDriverHeadShot"];
           $this->WarthogTurretKills = $dataRow["WarthogTurretKills"];
           $this->WarthogTurretDeaths = $dataRow["WarthogTurretDeaths"];
           $this->WarthogTurretSuicide = $dataRow["WarthogTurretSuicides"];
           $this->WarthogTurretShotsFired = $dataRow["WarthogTurretShotsFired"];
           $this->WarthogTurretShotsHit = $dataRow["WarthogTurretShotsHit"];
           $this->WarthogTurretHeadshot = $dataRow["WarthogTurretHeadShot"];
           $this->WraithKills = $dataRow["WraithKills"];
           $this->WraithDeaths = $dataRow["WraithDeaths"];
           $this->WraithSuicide = $dataRow["WraithSuicides"];
           $this->WraithShotsFired = $dataRow["WraithShotsFired"];
           $this->WraithShotsHit = $dataRow["WraithShotsHit"];
           $this->WraithHeadshot = $dataRow["WraithHeadShot"];
           $this->ScorpionCannonKills = $dataRow["ScorpionCannonKills"];
           $this->ScorpionCannonDeaths = $dataRow["ScorpionCannonDeaths"];
           $this->ScorpionCannonSuicide = $dataRow["ScorpionCannonSuicides"];
           $this->ScorpionCannonShotsFired = $dataRow["ScorpionCannonShotsFired"];
           $this->ScorpionCannonShotsHit = $dataRow["ScorpionCannonShotsHit"];
           $this->ScorpionCannonHeadshot = $dataRow["ScorpionCannonHeadShot"];
           $this->AssultBombKills = $dataRow["AssultBombKills"];
           $this->AssultBombDeaths = $dataRow["AssultBombDeaths"];
           $this->AssultBombSuicide = $dataRow["AssultBombSuicides"];
           $this->AssultBombShotsFired = $dataRow["AssultBombShotsFired"];
           $this->AssultBombShotsHit = $dataRow["AssultBombShotsHit"];
           $this->AssultBombHeadshot = $dataRow["AssultBombHeadShot"];
        }
    }
?>